### ISSUE TITLE
tracking eddy from sea level anomaly in win10

### ISSUE THREAD

**Issue by limaolin1981611** [AntSimi/py-eddy-tracker#134]
10 Anticyclonic detection  files:
Anticyclonic_adt_filter_400_PacificNW_20220101.nc
Anticyclonic_adt_filter_400_PacificNW_20220102.nc
......
Anticyclonic_adt_filter_400_PacificNW_20220110.nc

```yaml
PATHS:
  # Files produces with EddyIdentification
  FILES_PATTERN: D:\Project\MesoscaleEddy\python\py-eddy-tracker-master\examples\02_eddy_identification\out\Anticyclonic_adt*.nc
  SAVE_DIR: D:\Project\MesoscaleEddy\python\py-eddy-tracker-master\examples\02_eddy_identification\out\

# Number of consecutive timesteps with missing detection allowed
VIRTUAL_LENGTH_MAX: 1
# Minimal number of timesteps to considered as a long trajectory
TRACK_DURATION_MIN: 10
```
```bash
(base) PS D:\Project\MesoscaleEddy\python\py-eddy-tracker-master\examples\02_eddy_identification> EddyTracking conf.yaml -v DEBUG
[36mINFO[0m 2022-02-10 20:51:33,222 [36meddies[0m.[36mbrowse_dataset_in[0m :
        [36mSearch files : D:\Project\MesoscaleEddy\python\py-eddy-tracker-master\examples\02_eddy_identification\out\Anticyclonic_adt*.nc[0m
[36mINFO[0m 2022-02-10 20:51:33,223 [36meddies[0m.[36mbrowse_dataset_in[0m :
        [36m10 grids available[0m
[34m   DEBUG[0m 2022-02-10 20:51:33,224 [34m eddies[0m.[34m        browse_dataset_in[0m :
        [34m   Pattern date : .*_([0-9]*?).[nz].*[0m
Traceback (most recent call last):
  File "C:\Users\Apple\anaconda3\Scripts\EddyTracking-script.py", line 11, in <module>
    load_entry_point('pyEddyTracker==0+unknown', 'console_scripts', 'EddyTracking')()
  File "c:\users\apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\appli\eddies.py", line 223, in eddies_tracking
    blank_period=args.blank_period,
  File "c:\users\apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\appli\eddies.py", line 315, in track
    datasets = browse_dataset_in(**kw)
  File "c:\users\apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\appli\eddies.py", line 280, in browse_dataset_in
    raise Exception("Several timesteps in grid dataset %s" % steps)
Exception: Several timesteps in grid dataset [      4363803490384  213713157472651184  288687161241819894
  502744628077335308  622364944769004947 1297334106293405581
 2045295519947581540 3967103881031319305 4297561314611494392]
```

**Comment by limaolin1981611** [comment]
I have run the code in Mac, the output was right. How can I use it in windows?

**Comment by AntSimi** [comment]
Like ask [here](https://github.com/AntSimi/py-eddy-tracker/issues/130#issuecomment-1031219785) could you please explain how you install py eddy tracker on windows?
