### ISSUE TITLE
errors of grid_count in pet_birth_and_death.py

### ISSUE THREAD

**Issue by limaolin1981611** [AntSimi/py-eddy-tracker#136]
1.errors as follows:
```python
C:\Users\Apple\anaconda3\python.exe D:/Project/MesoscaleEddy/python/py-eddy-tracker-master/examples/10_tracking_diagnostics/pet_birth_and_death.py
File was created with py-eddy-tracker version 'None' but software version is '0.0'
File was created with py-eddy-tracker version 'None' but software version is '0.0'
Traceback (most recent call last):
  File "D:/Project/MesoscaleEddy/python/py-eddy-tracker-master/examples/10_tracking_diagnostics/pet_birth_and_death.py", line 54, in <module>
    g_c_first = c.first_obs().grid_count(bins, intern=True)
  File "C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py", line 2168, in grid_count
    regular_grid.y_c,
  File "C:\Users\Apple\anaconda3\lib\site-packages\numba\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\Apple\anaconda3\lib\site-packages\numba\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\Apple\anaconda3\lib\site-packages\numba\six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, A) and array(float64, 1d, C) for 'x_', defined at C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py (2379)

File "C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py", line 2379:
def grid_count_pixel_in(
    <source elided>
    for i_ in range(nb):
        x_, y_, x_ref_ = x[i_], y[i_], x_ref[i_]
        ^

[1] During: typing of assignment at C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py (2380)

File "C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py", line 2380:
def grid_count_pixel_in(
    <source elided>
        x_, y_, x_ref_ = x[i_], y[i_], x_ref[i_]
        x_ = (x_ - x_ref_) % 360 + x_ref_
        ^


Process finished with exit code 1
```

2. If I changed 
```python
g_c_first = c.first_obs().grid_count(bins, intern=True)
```
 to 
```python
g_c_first = c.first_obs().grid_count(bins, intern=True, center=True)
```
, It's correct, but the fig was different.
![Figure_1](https://user-images.githubusercontent.com/62914884/153755008-e0342d28-622f-4ebc-9f18-6602705d323e.png)

[pet_birth_and_death.zip](https://github.com/AntSimi/py-eddy-tracker/files/8055588/pet_birth_and_death.zip)

**Comment by AntSimi** [comment]
How did you get/compute input file?
It's look like a numba problem, which version of numba and numpy did you use?
If you specify `center=True` grid_count method  count how many center are in each pixel.
If `center=False` method count how many time a pixel are enclosed in an eddy contour.
It give two differents informations.

**Comment by limaolin1981611** [comment]
numba  0.55.1
numpy  1.18.1

**Comment by limaolin1981611** [comment]
1. If I set center=False, it's wrong as follows:
Traceback (most recent call last):
  File "D:/Project/MesoscaleEddy/python/py-eddy-tracker-master/examples/10_tracking_diagnostics/pet_birth_and_death.py", line 54, in <module>
    g_c_first = c.first_obs().grid_count(bins, intern=True, center=False)
  File "C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py", line 2168, in grid_count
    regular_grid.y_c,
  File "C:\Users\Apple\anaconda3\lib\site-packages\numba\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\Apple\anaconda3\lib\site-packages\numba\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\Apple\anaconda3\lib\site-packages\numba\six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, A) and array(float64, 1d, C) for 'x_', defined at C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py (2379)

File "C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py", line 2379:
def grid_count_pixel_in(
    <source elided>
    for i_ in range(nb):
        x_, y_, x_ref_ = x[i_], y[i_], x_ref[i_]
        ^

[1] During: typing of assignment at C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py (2380)

File "C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py", line 2380:
def grid_count_pixel_in(
    <source elided>
        x_, y_, x_ref_ = x[i_], y[i_], x_ref[i_]
        x_ = (x_ - x_ref_) % 360 + x_ref_
        ^


Process finished with exit code 1

**Comment by limaolin1981611** [comment]
The input file was forms your "eddies_med_adt_allsat_dt2018".

**Comment by limaolin1981611** [comment]
I have compared the "pet_pixel_used.py" and "pet_center_count.py",  the difference was "grid_count(bins, intern=True)" in "pet_pixel_used.py" ,"grid_count(bins, intern=True, center=True)" in "pet_center_count.py".
When I run the  "pet_pixel_used.py" , the erros as follows:
Traceback (most recent call last):
  File "D:/Project/MesoscaleEddy/python/py-eddy-tracker-master/examples/10_tracking_diagnostics/pet_pixel_used.py", line 40, in <module>
    g_a = a.grid_count(bins, intern=True)
  File "C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py", line 2168, in grid_count
    regular_grid.y_c,
  File "C:\Users\Apple\anaconda3\lib\site-packages\numba\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\Apple\anaconda3\lib\site-packages\numba\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\Apple\anaconda3\lib\site-packages\numba\six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, A) and array(float64, 1d, C) for 'x_', defined at C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py (2379)

File "C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py", line 2379:
def grid_count_pixel_in(
    <source elided>
    for i_ in range(nb):
        x_, y_, x_ref_ = x[i_], y[i_], x_ref[i_]
        ^

[1] During: typing of assignment at C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py (2380)

File "C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.7.egg\py_eddy_tracker\observations\observation.py", line 2380:
def grid_count_pixel_in(
    <source elided>
        x_, y_, x_ref_ = x[i_], y[i_], x_ref[i_]
        x_ = (x_ - x_ref_) % 360 + x_ref_
        ^


Process finished with exit code 1

**Comment by limaolin1981611** [comment]
How Can I correct the erros?
