### ISSUE TITLE
Eddy detection for POP3

### ISSUE THREAD

**Issue by zmbvsky** [AntSimi/py-eddy-tracker#138]
Hi, 
I'm a Master's Student at the University of Hamburg and I'd like to apply the eddy detection and also the tracking to a dataset derived from the Parallel Ocean Program (POP). 
The installation went well and the detection is working for the given example file (nrt_global_allsat_phy_l4_20190223_20190226.nc). 
I tried to put all my data into a NetCDF with similar format as shown in the example. 
```python
 Source:
           20010101format.nc
Format:
           netcdf4_classic
Dimensions:
           time      = 1
           latitude  = 1200
           longitude = 3600
Variables:
    time     
           Size:       1x1
           Dimensions: time
           Datatype:   single
    latitude 
           Size:       1200x1
           Dimensions: latitude
           Datatype:   single
    longitude
           Size:       3600x1
           Dimensions: longitude
           Datatype:   single
    SSH      
           Size:       3600x1200x1
           Dimensions: longitude,latitude,time
           Datatype:   single
    UVEL     
           Size:       3600x1200x1
           Dimensions: longitude,latitude,time
           Datatype:   single
    VVEL     
            Size:       3600x1200x1
            Dimensions: longitude,latitude,time
            Datatype:   single
```
When I try to run the eddy detection on this dataset, I get the following error message: 

```python
  C:\Users\felix\anaconda3>EddyId share/20010101format.nc 20010101 SSH UVEL VVEL longitude latitude ./data_out -v INFO
 ←[30;47mWARNING←[0m 2022-02-21 15:38:37,567 ←[30;47mgrid←[0m.←[30;47m__init__←[0m :
        ←[30;47mWe assume pixel position of grid is centered for share/20010101format.nc←[0m
←[36mINFO←[0m 2022-02-21 15:38:37,571 ←[36mgrid←[0m.←[36msetup_coordinates←[0m :
        ←[36mGrid center←[0m
Traceback (most recent call last):
  File "c:\users\felix\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\felix\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\felix\anaconda3\Scripts\EddyId.exe\__main__.py", line 7, in <module>
  File "c:\users\felix\anaconda3\lib\site-packages\py_eddy_tracker\appli\grid.py", line 135, in eddy_id
    a, c = identification(
  File "c:\users\felix\anaconda3\lib\site-packages\py_eddy_tracker\appli\grid.py", line 185, in identification
    grid.bessel_high_filter(h, cut_wavelength, **kw_filter)
  File "c:\users\felix\anaconda3\lib\site-packages\py_eddy_tracker\dataset\grid.py", line 1496, in bessel_high_filter
    data_out = self.convolve_filter_with_dynamic_kernel(
  File "c:\users\felix\anaconda3\lib\site-packages\py_eddy_tracker\dataset\grid.py", line 1383, in convolve_filter_with_dynamic_kernel
    kernel = kernel_func(lat, **kwargs_func)
  File "c:\users\felix\anaconda3\lib\site-packages\py_eddy_tracker\dataset\grid.py", line 1342, in kernel_bessel
    kernel[0, half_y_pt * order] = pi
IndexError: index 0 is out of bounds for axis 0 with size 0
```
Since I'm not very familiar with Python, it's very hard for me to understand the problem in this case and I would be very happy about any help or suggestions. 
The only difference I see between my file and the given example are the missing longitude and latitude bounds. Are they required for the eddy detection? 

I hope I provided all necessary informations and would be very happy about help, solving this problem. 
Cheers 
Felix

**Comment by AntSimi** [comment]
Several things:

- You must specify unit for variable
- Could you give min and max of latitude
- How was the original format of your data
- SSH, UVEL, VVEL use int32 without scale_factor is it correct?

**Comment by zmbvsky** [comment]
Oh, I thought the attributes are only for documentation and not used by the algorithm.

- Min(latitude)=-78.472862, Max(latitude)=1.7497509 since POP is using a tripole grid I want to focus on the southern hemisphere where the grid is regular. 
- The original data comes from several NetCDFs with the variables given in single prec. 
- You are right, I'm missing the scale_factor here

I will add units and scale_factor to the attributes and try again. 
Thank you a lot.

**Comment by zmbvsky** [comment]
Hi, 
I added units, scale_factor and the according _FillValues to my data but I'm still getting the same error. 

```python
Source:
           C:\Users\felix\anaconda3\share\20010101format.nc
Format:
           netcdf4
Dimensions:
           time      = 1
           latitude  = 1200
           longitude = 3600
           nv        = 2
Variables:
    time     
           Size:       1x1
           Dimensions: time
           Datatype:   single
           Attributes:
                       units = 'days since 1950-01-01 00:00:00'
    latitude 
           Size:       1200x1
           Dimensions: latitude
           Datatype:   single
           Attributes:
                       units  = 'degrees_north'
                       bounds = 'lat_bnds'
    longitude
           Size:       3600x1
           Dimensions: longitude
           Datatype:   single
           Attributes:
                       units  = 'degrees_east'
                       bounds = 'lon_bnds'
    SSH      
           Size:       3600x1200x1
           Dimensions: longitude,latitude,time
           Datatype:   int32
           Attributes:
                       _FillValue   = -9999
                       units        = 'm'
                       scale_factor = 0.0001
    UVEL     
           Size:       3600x1200x1
           Dimensions: longitude,latitude,time
           Datatype:   int32
           Attributes:
                       _FillValue   = 0
                       units        = 'm/s'
                       scale_factor = 0.0001
    VVEL     
           Size:       3600x1200x1
           Dimensions: longitude,latitude,time
           Datatype:   int32
           Attributes:
                       _FillValue   = 0
                       units        = 'm/s'
                       scale_factor = 0.0001
    lat_bnds 
           Size:       2x1200
           Dimensions: nv,latitude
           Datatype:   single
           Attributes:
                       units = 'degrees_north'
    lon_bnds 
           Size:       2x3600
           Dimensions: nv,longitude
           Datatype:   single
           Attributes:
                       units = 'degrees_east'
```

Do you have any suggestion what I can do to rule out what's going wrong? 
I thought about filling up the "woking example" with my own data, to see if it has something to do with my data itself.

**Comment by AntSimi** [comment]
Could you share netcdf file use in input of EddyDetection?

**Comment by zmbvsky** [comment]
Hey, 
I had to reduce the dataset from 1200x3600 (latitude x longitude) to 1200x1200 grid points to make it smaller than 25mb. 
The given error is still the same. 
[20010101format.zip](https://github.com/AntSimi/py-eddy-tracker/files/8140757/20010101format.zip)

**Comment by AntSimi** [comment]
Error message was not obvious, maybe i will add some code for warning.
But coordinates must be strictly increasing. Your longitude variable is incorrect.
Your SSH variable have an incorrect fillvalue, this code must return matrix without -9999....:
```python
from netCDF4 import Dataset
with Dataset('20010101format.nc') as h:
    print(h.variables['SSH'][:])
```
output
```python
[[[-9999.0 -9999.0 -9999.0 ... -9999.0 -9999.0 -9999.0]
  [-9999.0 -9999.0 -9999.0 ... -9999.0 -9999.0 -9999.0]
  [-9999.0 -9999.0 -9999.0 ... -9999.0 -9999.0 -9999.0]
  ...
  [0.12240000000000001 0.1228 0.1221 ... -9999.0 -9999.0 -9999.0]
  [0.1297 0.1288 0.1291 ... -9999.0 -9999.0 -9999.0]
  [0.1365 0.1364 0.1353 ... -9999.0 -9999.0 -9999.0]]]
```

Last advice for filtering step, 700 km is better than 500km and maybe use only order 1.

**Comment by zmbvsky** [comment]
Thank you very much for your help. I really apreciate it. 
I will fix the issues and I'm really looking forward to study the results.
