### ISSUE TITLE
Tracking exception: too many iteration

### ISSUE THREAD

**Issue by AntSimi** [AntSimi/py-eddy-tracker#15]
raise Exception('To many iteration: %d' % security_increment)
Exception: To many iteration: 9

How to solve the issue while tracking

_Originally posted by @abhijithpkurian in https://github.com/AntSimi/py-eddy-tracker/issues/14#issuecomment-659634113_

**Comment by AntSimi** [comment]
To help you, i will need more context:

1. Maybe activate DEBUG to have more information?
2. Did you take a look at identification files, to check detection?
3. How did you run tracking, with wchich parameters?

**Comment by abhijithpkurian** [comment]
Traceback (most recent call last):
  File "/home/akurian/anaconda3/bin/EddyTracking", line 4, in <module>
    __import__('pkg_resources').run_script('pyEddyTracker==3.0.0', 'EddyTracking')
  File "/home/akurian/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/akurian/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/akurian/anaconda3/lib/python3.7/site-packages/pyEddyTracker-3.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/EddyTracking", line 99, in <module>
    CORRESPONDANCES.track()
  File "/home/akurian/anaconda3/lib/python3.7/site-packages/pyEddyTracker-3.0.0-py3.7-linux-x86_64.egg/py_eddy_tracker/tracking.py", line 332, in track
    i_previous, i_current, association_cost = self.previous_obs.tracking(self.current_obs)
  File "/home/akurian/anaconda3/lib/python3.7/site-packages/pyEddyTracker-3.0.0-py3.7-linux-x86_64.egg/py_eddy_tracker/observations.py", line 616, in tracking
    i_self, i_other = self.solve_function(cost_mat)
  File "/home/akurian/anaconda3/lib/python3.7/site-packages/pyEddyTracker-3.0.0-py3.7-linux-x86_64.egg/py_eddy_tracker/observations.py", line 593, in solve_function
    return where(self.solve_simultaneous(cost_matrix))
  File "/home/akurian/anaconda3/lib/python3.7/site-packages/pyEddyTracker-3.0.0-py3.7-linux-x86_64.egg/py_eddy_tracker/observations.py", line 526, in solve_simultaneous
    raise Exception('To many iteration: %d' % security_increment)
Exception: To many iteration: 5

**Comment by abhijithpkurian** [comment]
# Two diagnostics, based on SLA (e.g., Chelton et al, 2011)
# or the Q-parameter (e.g., Kurian et al, 2011) are available
DIAGNOSTIC_TYPE: 'SLA'

PATHS:
  # Files produces with EddyIdentification
  FILES_PATTERN: /home/akurian/what/2018O/Anticyclonic_*.nc
  # Path and filename of Chelton et al (1998) Rossby radius data
  # Obtain file from:
  # http://www-po.coas.oregonstate.edu/research/po/research/rossby_radius/
  RW_PATH: '/home/emason/Dropbox/rossrad.dat'
  # Path for saving of outputs
  SAVE_DIR: '/home/akurian/what/2018W/'

# Minimum number of observations to store eddy
VIRTUAL_LENGTH_MAX: 0
TRACK_DURATION_MIN: 4


#CLASS:
#    MODULE: py_eddy_tracker.featured_tracking.old_tracker_reference
#    CLASS: CheltonTracker

**Comment by AntSimi** [comment]
When you run EddyTracking add -v DEBUG
