### ISSUE TITLE
How to generate tracking files named with .zarr？

### ISSUE THREAD

**Issue by yangfan143** [AntSimi/py-eddy-tracker#182]
Thank you very much for your team's genius code！I have learned the pet for a longlong time，but my lace of knowledge couldnt help me finding out how to combine the idification result，to make it a nc or zarr file without lossing related information.In other words，in 
 the tracking step,I coundt I can't generate the cyclonic.zarr file for tracing from code.is there any instruction for zarr files?I can't thank you enough to  your generous help！！

**Comment by yangfan143** [comment]
Thanks a lot !! I make a file named with conf.yaml and change the filepath,but while running the code `"EddyTracking` conf.yaml -v DEBUG"` after cmd activates the virtual environment, I get the result `"failed to create process."`Could you please tell me what should I do~

**Comment by AntSimi** [comment]
Could you share traceback?

**Comment by yangfan143** [comment]
`PS D:\BaiduSyncdisk\latest work\1code\1py-eddy\1py-eddy-tracker-master\examples\08_tracking_manipulation> EddyTracking conf.yaml -v DEBUG      
D:\Software\anaconda\lib\site-packages\numpy\__init__.py:148: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-
the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "D:\Software\anaconda\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "D:\Software\anaconda\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "D:\Software\anaconda\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\anaconda\Scripts\EddyTracking-script.py", line 33, in <module>
    sys.exit(load_entry_point('pyEddyTracker==0+unknown', 'console_scripts', 'EddyTracking')())
  File "D:\Software\anaconda\Scripts\EddyTracking-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "D:\Software\anaconda\lib\importlib\metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "D:\Software\anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Software\anaconda\lib\site-packages\pyeddytracker-0+unknown-py3.9.egg\py_eddy_tracker\__init__.py", line 27, in <module>
    import zarr
  File "D:\Software\anaconda\lib\site-packages\zarr\__init__.py", line 2, in <module>
    from zarr.codecs import *
  File "D:\Software\anaconda\lib\site-packages\zarr\codecs.py", line 2, in <module>
    from numcodecs import *

Please note and check the following:

  * The Python version is: Python3.9 from "D:\Software\anaconda\python.exe"
  * The NumPy version is: "1.21.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: 找不到指定的模块。
`

**Comment by acr604** [comment]
Hi,
I am trying to plot histograms of Eddy characteristics for a 3 year period.
The "lifetime statistics" section of the document shows loading a single zarr file.
How can I convert my daily netcdf Id and track files into such a single zarr file ?
