### ISSUE TITLE
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

### ISSUE THREAD

**Issue by marimpacheco** [AntSimi/py-eddy-tracker#185]
After installation, I tried to run the example in the terminal, then I came up with the following error:

Example:

```bash
EddyId share/nrt_global_allsat_phy_l4_20190223_20190226.nc 20190223 \
    adt ugos vgos longitude latitude \
    out_directory -v DEBUG
```

**Error**

```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "/gxfs_home/geomar/smomw541/miniconda3/envs/py3_std/bin/EddyId", line 33, in <module>
    sys.exit(load_entry_point('pyEddyTracker==3.6.1+2.gc455bc6', 'console_scripts', 'EddyId')())
  File "/gxfs_home/geomar/smomw541/miniconda3/envs/py3_std/bin/EddyId", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/gxfs_home/geomar/smomw541/miniconda3/envs/py3_std/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/gxfs_home/geomar/smomw541/miniconda3/envs/py3_std/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/gxfs_home/geomar/smomw541/miniconda3/envs/py3_std/lib/python3.9/site-packages/pyEddyTracker-3.6.1+2.gc455bc6-py3.9.egg/py_eddy_tracker/appli/grid.py", line 8, in <module>
    from ..dataset.grid import RegularGridDataset, UnRegularGridDataset
  File "/gxfs_home/geomar/smomw541/miniconda3/envs/py3_std/lib/python3.9/site-packages/pyEddyTracker-3.6.1+2.gc455bc6-py3.9.egg/py_eddy_tracker/dataset/grid.py", line 52, in <module>
    from ..eddy_feature import Amplitude, Contours
  File "/gxfs_home/geomar/smomw541/miniconda3/envs/py3_std/lib/python3.9/site-packages/pyEddyTracker-3.6.1+2.gc455bc6-py3.9.egg/py_eddy_tracker/eddy_feature.py", line 25, in <module>
    from .poly import winding_number_poly
  File "/gxfs_home/geomar/smomw541/miniconda3/envs/py3_std/lib/python3.9/site-packages/pyEddyTracker-3.6.1+2.gc455bc6-py3.9.egg/py_eddy_tracker/poly.py", line 8, in <module>
    from Polygon import Polygon
  File "/gxfs_home/geomar/smomw541/miniconda3/envs/py3_std/lib/python3.9/site-packages/Polygon/__init__.py", line 5, in <module>
    from Polygon.cPolygon import *
ImportError: numpy.core.multiarray failed to import
```

I also tried in jupyter lab just to import some of the classes and got apparently the same error: 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In [3], line 2
      1 from py_eddy_tracker import data
----> 2 from py_eddy_tracker.dataset.grid import RegularGridDataset
      3 from py_eddy_tracker.eddy_feature import Contours

File ~/miniconda3/envs/py3_std/lib/python3.9/site-packages/pyEddyTracker-3.6.1+2.gc455bc6-py3.9.egg/py_eddy_tracker/dataset/grid.py:52
     49 from scipy.special import j1
     51 from .. import VAR_DESCR
---> 52 from ..eddy_feature import Amplitude, Contours
     53 from ..generic import (
     54     bbox_indice_regular,
     55     coordinates_to_local,
   (...)
     60     uniform_resample,
     61 )
     62 from ..observations.observation import EddiesObservations

File ~/miniconda3/envs/py3_std/lib/python3.9/site-packages/pyEddyTracker-3.6.1+2.gc455bc6-py3.9.egg/py_eddy_tracker/eddy_feature.py:25
     11 from numba import njit, types as numba_types
     12 from numpy import (
     13     array,
     14     concatenate,
   (...)
     22     zeros,
     23 )
---> 25 from .poly import winding_number_poly
     27 logger = logging.getLogger("pet")
     30 class Amplitude(object):

File ~/miniconda3/envs/py3_std/lib/python3.9/site-packages/pyEddyTracker-3.6.1+2.gc455bc6-py3.9.egg/py_eddy_tracker/poly.py:8
      2 """
      3 Method for polygon
      4 """
      6 import heapq
----> 8 from Polygon import Polygon
      9 from numba import njit, prange, types as numba_types
     10 from numpy import arctan, array, concatenate, empty, nan, ones, pi, where, zeros

File ~/miniconda3/envs/py3_std/lib/python3.9/site-packages/Polygon/__init__.py:5
      1 # -*- coding: utf-8 -*-
      2 
      3 
      4 # import everything from cPolygon
----> 5 from Polygon.cPolygon import *
      7 # keep namespace clean
      8 __version__ = version

ImportError: numpy.core.multiarray failed to import
```
I have the numpy version 1.22.4, which had been downgraded to fulfill the py_eddy_tracker requirements. I use miniconda and have all the packages required.

**Comment by AntSimi** [comment]
How did you install extern module(like numpy)? with pip or conda or with `python setup.py install`

**Comment by marimpacheco** [comment]
Most of the modules were installed with conda (conda-forge). However I had gone the whole installation section (pip install numpy scipy...'. Now they're listed as:
```
# Name                    Version                   Build  Channel
numpy                     1.22.4                   pypi_0    pypi
scipy                     1.9.1            py39h8ba3f38_0    conda-forge
netcdf4                   1.5.8                    pypi_0    pypi
matplotlib                3.6.1            py39hf3d152e_0    conda-forge
matplotlib-base           3.6.1            py39hf9fd14e_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
opencv-python             4.7.0.68                 pypi_0    pypi
pyyaml                    6.0              py39hb9d737c_4    conda-forge
polygon3                  3.0.9.1                  pypi_0    pypi
```

**Comment by marimpacheco** [comment]
No, I was using an old environment. I had to create a new one and it worked, thanks!
