### ISSUE TITLE
No such file or directory: '/home/emason/toto/'

### ISSUE THREAD

**Issue by KMartin0013** [AntSimi/py-eddy-tracker#243]
Many thanks for your contribution on this PET project. I try to run the codes in the 'Quick Use' section. I succeeded for the eddy identification, but got stuck on the tracking code. Below is the error information I got on my Mac (similar issues also occur in Windows):

```
(.conda) (base) martindeMacBook-Pro:py-eddy-tracker martin$ EddyTracking ./share/tracking.yaml
Traceback (most recent call last):
  File "/Users/martin/Desktop/desk_program/python/Eddy_tracer/.conda/bin/EddyTracking", line 33, in <module>
    sys.exit(load_entry_point('pyEddyTracker==3.6.1+12.gc7430ce', 'console_scripts', 'EddyTracking')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/Desktop/desk_program/python/Eddy_tracer/.conda/lib/python3.11/site-packages/pyEddyTracker-3.6.1+12.gc7430ce-py3.11.egg/py_eddy_tracker/appli/eddies.py", line 208, in eddies_tracking
    mkdir(save_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/emason/toto/'
```

Could you tell me there is something wrong on the setup or just another case due to system incompatibility on Mac (or Windows). Thank you.

**Comment by KMartin0013** [comment]
Sorry, It seems that the files_pattern should be changed manually in the tracking.yaml. I will chose the issue here.
