### ISSUE TITLE
EddyID error

### ISSUE THREAD

**Issue by evanmason** [AntSimi/py-eddy-tracker#35]
I run this:
`EddyId -v DEBUG /home/sample/SSH_UV_surface_20140428.nc 20140428  sossheig vozocrtx vomecrty lon lat .`

but get the error: 

```python
DEBUG 2020-11-04 13:12:51,135 	grid.	eddy_identification :
						doing collection 1015, contour value 0.0080, 5 paths
Traceback (most recent call last):
  File "/home/emason/VENVP3/bin/EddyId", line 11, in <module>
    load_entry_point('pyEddyTracker==0+untagged.442.g31abfe8', 'console_scripts', 'EddyId')()
  File "/home/emason/VENVP3/lib/python3.7/site-packages/pyEddyTracker-0+untagged.442.g31abfe8-py3.7.egg/py_eddy_tracker/appli/grid.py", line 92, in eddy_id
    **kwargs
  File "/home/emason/VENVP3/lib/python3.7/site-packages/pyEddyTracker-0+untagged.442.g31abfe8-py3.7.egg/py_eddy_tracker/appli/grid.py", line 119, in identification
    return grid.eddy_identification(h, u, v, date, **kwargs)
  File "/home/emason/VENVP3/lib/python3.7/site-packages/pyEddyTracker-0+untagged.442.g31abfe8-py3.7.egg/py_eddy_tracker/dataset/grid.py", line 797, in eddy_identification
    pixel_min=pixel_limit[0],
  File "/home/emason/VENVP3/lib/python3.7/site-packages/pyEddyTracker-0+untagged.442.g31abfe8-py3.7.egg/py_eddy_tracker/dataset/grid.py", line 927, in get_uavg
    max_average_speed = self.speed_coef_mean(original_contour)
  File "/home/emason/VENVP3/lib/python3.7/site-packages/pyEddyTracker-0+untagged.442.g31abfe8-py3.7.egg/py_eddy_tracker/dataset/grid.py", line 1789, in speed_coef_mean
    nan_remove=True,
  File "/home/emason/VENVP3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/emason/VENVP3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/home/emason/VENVP3/lib/python3.7/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:

 >>> getitem(bool, UniTuple(int64 x 2))

There are 22 candidate implementations:
     - Of which 22 did not match due to:
     Overload of function 'getitem': File: <numerous>: Line N/A.
       With argument(s): '(bool, UniTuple(int64 x 2))':
      No match.

During: typing of intrinsic-call at /home/emason/VENVP3/lib/python3.7/site-packages/pyEddyTracker-0+untagged.442.g31abfe8-py3.7.egg/py_eddy_tracker/generic.py (222)

File "../../../VENVP3/lib/python3.7/site-packages/pyEddyTracker-0+untagged.442.g31abfe8-py3.7.egg/py_eddy_tracker/generic.py", line 222:
def interp2d_geo(x_g, y_g, z_g, m_g, x, y):
    <source elided>
        z11 = z_g[i1, j1]
        if m_g[i0, j0] or m_g[i0, j1] or m_g[i1, j0] or m_g[i1, j1]:
        ^

During: resolving callee type: type(CPUDispatcher(<function interp2d_geo at 0x7f2757404b90>))
During: typing of call at /home/emason/VENVP3/lib/python3.7/site-packages/pyEddyTracker-0+untagged.442.g31abfe8-py3.7.egg/py_eddy_tracker/dataset/grid.py (125)

During: resolving callee type: type(CPUDispatcher(<function interp2d_geo at 0x7f2757404b90>))
During: typing of call at /home/emason/VENVP3/lib/python3.7/site-packages/pyEddyTracker-0+untagged.442.g31abfe8-py3.7.egg/py_eddy_tracker/dataset/grid.py (125)


File "../../../VENVP3/lib/python3.7/site-packages/pyEddyTracker-0+untagged.442.g31abfe8-py3.7.egg/py_eddy_tracker/dataset/grid.py", line 125:
def mean_on_regular_contour(
    <source elided>
    x_new, y_new = uniform_resample(x_val, y_val, num_fac, fixed_size)
    values = interp2d_geo(x_g, y_g, z_g, m_g, x_new[1:], y_new[1:])
    ^
```

Any ideas?

**Comment by AntSimi** [comment]
could you share nc file?

**Comment by evanmason** [comment]
[](url)

**Comment by evanmason** [comment]
[ncfile.tar.gz](https://github.com/AntSimi/py-eddy-tracker/files/5488061/ncfile.tar.gz)

**Comment by evanmason** [comment]
[ncfile.tar.gz](https://github.com/AntSimi/py-eddy-tracker/files/5488140/ncfile.tar.gz)

**Comment by AntSimi** [comment]
Your file isn't a regular grid, so you need to add `--unregular` option, your coordinates are `nav_lon and nav_lat` and EddyId script didn't provide filter for unregulargrid so i had ```--cut 0``` option to avoid filter.
```bash
EddyId -v DEBUG SSH_UV_surface_20140428.nc 20140428 sossheig vozocrtx vomecrty nav_lon nav_lat . --unregular --cut 0
```

Maybe we could had some check to throw an earlier error message

**Comment by evanmason** [comment]
Perfect, thanks
