### ISSUE TITLE
llvmlite distribution not found

### ISSUE THREAD

**Issue by evanmason** [AntSimi/py-eddy-tracker#39]
When running `python3.8 setup.py install --user` I get this error:
```
Traceback (most recent call last):
  File "/home/acad/ulg-mast/emason/.local/bin/EddyId", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/softs/python/3.8.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/softs/python/3.8.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/softs/python/3.8.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/softs/python/3.8.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/softs/python/3.8.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/softs/python/3.8.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'llvmlite<0.36,>=0.35.0rc3' distribution was not found and is required by numba
```
Looking here `https://pypi.org/simple/llvmlite/` indeed 0.36 is not listed.  How should we proceed?

**Comment by AntSimi** [comment]
Hi,
I think you install a recent version of numba and your installer don't have acces to [recent llvmlite](https://pypi.org/project/llvmlite/#history), before to install py_eddy_tracker try to install an older version of numba like 0.51.2.
