### ISSUE TITLE
UnRegularGridDataset error: 'AttributeError: 'ModulePassManager' object has no attribute 'add_loop_rotate_pass'' 

### ISSUE THREAD

**Issue by evanmason** [AntSimi/py-eddy-tracker#41]
The file `make_BlackSea_eddies.py` iterates over a time series of SSH,U,V data and saves the eddy properties.  When I run this script inside an IPython session it works fine, but when used at the terminal it produces the error below:
```
(VENV) [emason@nic4.login BS_code]$ python make_BlackSea_eddies.py
Traceback (most recent call last):
  File "make_BlackSea_eddies.py", line 10, in <module>
    from py_eddy_tracker.dataset.grid import UnRegularGridDataset
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/py_eddy_tracker/dataset/grid.py", line 11, in <module>
    from numba import njit
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/__init__.py", line 212, in <module>
    import numba.typed
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/typed/__init__.py", line 1, in <module>
    from .typeddict import Dict
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/typed/typeddict.py", line 22, in <module>
    @njit
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/decorators.py", line 260, in njit
    return jit(*args, **kws)
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/decorators.py", line 183, in jit
    return wrapper(pyfunc)
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/decorators.py", line 212, in wrapper
    **dispatcher_args)
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/dispatcher.py", line 746, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/registry.py", line 47, in target_context
    return self._toplevel_target_context
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/utils.py", line 277, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/registry.py", line 31, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/base.py", line 259, in __init__
    self.init()
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/codegen.py", line 1086, in __init__
    self._init(self._llvm_module)
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/codegen.py", line 1108, in _init
    cost="cheap")
  File "/home/ulg/mast/emason/VENV/lib/python3.7/site-packages/numba-0.52.0-py3.7-linux-x86_64.egg/numba/core/codegen.py", line 1147, in _module_pass_manager
    pm.add_loop_rotate_pass()
AttributeError: 'ModulePassManager' object has no attribute 'add_loop_rotate_pass'
(VENV) [emason@nic4.login BS_code]$
```
The error is somewhere inside numba.  Any suggestions what causes this problem?

**Comment by AntSimi** [comment]
Hi,
Maybe with script it's better :) to understand.
But it's strange, it's just at the import

**Comment by evanmason** [comment]
Yeah, there's nothing special about the script:

```
# %run make_BlackSea_eddies.py

from glob import glob
from netCDF4 import Dataset
#import xarray as xr
from numpy import arange, array, nan
from datetime import datetime
from matplotlib import pyplot as plt
#from py_eddy_tracker.dataset.grid import RegularGridDataset
from py_eddy_tracker.dataset.grid import UnRegularGridDataset
from py_eddy_tracker import data
from py_eddy_tracker import start_logger


if __name__ == '__main__':

    plt.close('all')

    directory = '/marula/emason/BlackSea/Sample/'
    directory = '/home/ulg/mast/emason/BS_surface_fields/'
    ssh_files = 'SSH_UV_BlackSea_surface_????????.nc'


    ssh_files = sorted(glob(directory + ssh_files))

    lon_name, lat_name = 'nav_lon', 'nav_lat'
    ssh_name, u_name, v_name = 'sossheig', 'vozocrtx', 'vomecrty'


    for ssh_file in ssh_files:

        #g = UnRegularGridDataset(data.get_path(ssh_file), lon_name, lat_name)
        start_logger().setLevel('DEBUG')

        h = UnRegularGridDataset(data.get_path(ssh_file), lon_name, lat_name)

        date = ssh_file.rpartition('_')[-1].partition('.')[0]
        date = datetime(int(date[:4]), int(date[4:6]), int(date[6:]))

        # Identification every 2 mm
        h.high_filter('sossheig', w_cut=400)
        a, c = h.eddy_identification(ssh_name, u_name, v_name, date, 0.002, pixel_limit=(5, 2000), shape_error=55)

        with Dataset(date.strftime(directory + 'Anticyclonic_%Y%m%d.nc'), 'w') as h:
            a.to_netcdf(h)
        with Dataset(date.strftime(directory + 'Cyclonic_%Y%m%d.nc'), 'w') as h:
            c.to_netcdf(h)
```

**Comment by AntSimi** [comment]
OK, i ran same import i haven't an `Exception`, did you use same python between the 2 run?

**Comment by evanmason** [comment]
With ipython I have:
```
In [3]: import sys

In [4]: sys.version
Out[4]: '3.7.4 (default, Oct  1 2019, 22:23:57) \n[GCC 8.3.0]'
```

and in the terminal:
```
(VENV) [emason@nic4.login BS_code]$ python -V
Python 3.7.4
```

**Comment by abebeos** [comment]
This possibly helps:

Had the same error in a source-code build numba environment.

Was a version mismatch numba/llvmlite

Those work:

* llvmlite v0.35.0 
* numba 0.52.0
