### ISSUE TITLE
Numba/nopython error when using grid.count() function

### ISSUE THREAD

**Issue by MatthisAuger** [AntSimi/py-eddy-tracker#48]
Hi, I get this error when using grid.count() function on a TrackEddiesObsevations object. I wanted to reproduced the Birth and Death example with my dataset. It looks like every other method works fine, but grid.count() gives this error. 

Unfortunately I cannot attach the input file (netcdf format is not supported). 
Here is the code:

```python
from py_eddy_tracker import start_logger
from py_eddy_tracker.dataset.grid import UnRegularGridDataset
from py_eddy_tracker.observations.tracking import TrackEddiesObservations

cyc = TrackEddiesObservations.load_file("Cyclonic.nc")
t0, t1 = cyc.period
step = 0.5
bins = ((0, 360, step), (-75, -60, step))
kwargs = dict(cmap="terrain_r", factor=100 / (t1 - t0), name="count", vmin=0, vmax=1)
g_c_first = cyc.first_obs().grid_count(bins, intern=True)
```

I get this error:
```bash
> ---------------------------------------------------------------------------
> TypingError                               Traceback (most recent call last)
> <ipython-input-2-6b0b02b82e27> in <module>()
>       4 kwargs = dict(cmap="terrain_r", factor=100 / (t1 - t0), name="count", vmin=0, vmax=1)
>       5 
> ----> 6 g_c_first = cyc.first_obs().grid_count(bins, intern=True)
> 
> ~/.conda/envs/my_root/lib/python3.6/site-packages/pyEddyTracker-3.3.0+18.g40ef190-py3.6.egg/py_eddy_tracker/observations/observation.py in grid_count(self, bins, intern, center, filter)
>    1971                 regular_grid.x_size,
>    1972                 regular_grid.x_c,
> -> 1973                 regular_grid.y_c,
>    1974             )
>    1975             grid.mask = grid == 0
> 
> ~/.conda/envs/my_root/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
>     399                 e.patch_message(msg)
>     400 
> --> 401             error_rewrite(e, 'typing')
>     402         except errors.UnsupportedError as e:
>     403             # Something unsupported is present in the user code, add help info
> 
> ~/.conda/envs/my_root/lib/python3.6/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
>     342                 raise e
>     343             else:
> --> 344                 reraise(type(e), e, None)
>     345 
>     346         argtypes = []
> 
> ~/.conda/envs/my_root/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
>     666             value = tp()
>     667         if value.__traceback__ is not tb:
> --> 668             raise value.with_traceback(tb)
>     669         raise value
>     670 
> 
> TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> Cannot unify array(float32, 1d, A) and array(float64, 1d, C) for 'x_', defined at /usr/home/mauger/.conda/envs/my_root/lib/python3.6/site-packages/pyEddyTracker-3.3.0+18.g40ef190-py3.6.egg/py_eddy_tracker/observations/observation.py (2166)
> 
> File "../../../../../../../../usr/home/mauger/.conda/envs/my_root/lib/python3.6/site-packages/pyEddyTracker-3.3.0+18.g40ef190-py3.6.egg/py_eddy_tracker/observations/observation.py", line 2166:
> def grid_count_pixel_in(
>     <source elided>
>     for i_ in range(nb):
>         x_, y_, x_ref_ = x[i_], y[i_], x_ref[i_]
>         ^
> 
> [1] During: typing of assignment at /usr/home/mauger/.conda/envs/my_root/lib/python3.6/site-packages/pyEddyTracker-3.3.0+18.g40ef190-py3.6.egg/py_eddy_tracker/observations/observation.py (2167)
> 
> File "../../../../../../../../usr/home/mauger/.conda/envs/my_root/lib/python3.6/site-packages/pyEddyTracker-3.3.0+18.g40ef190-py3.6.egg/py_eddy_tracker/observations/observation.py", line 2167:
> def grid_count_pixel_in(
>     <source elided>
>         x_, y_, x_ref_ = x[i_], y[i_], x_ref[i_]
>         x_ = (x_ - x_ref_) % 360 + x_ref_
>         ^
> 
> This is not usually a problem with Numba itself but instead often caused by
> the use of unsupported features or an issue in resolving types.
> 
> To see Python/NumPy features supported by the latest release of Numba visit:
> http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
> and
> http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
> 
> For more information about typing errors and how to debug them visit:
> http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
> 
> If you think your code should work with Numba, please report the error message
> and traceback, along with a minimal reproducer at:
> https://github.com/numba/numba/issues/new
```
Thanks !

**Comment by AntSimi** [comment]
Could you check numpy version and numba version?

**Comment by MatthisAuger** [comment]
numba: 0.47.0
numpy: 1.18.1

**Comment by AntSimi** [comment]
Before to go deeper try to update numba because [0.47.0](https://github.com/numba/numba/blob/master/CHANGE_LOG#L1182) is quite old. I use also an old one but more recent **0.51.2**.

**Comment by MatthisAuger** [comment]
Looks like it was a numba version issue, it works fine now. Thanks.
